### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by erickzzh** [IBM/watson-nao-robot#22]
Hey I have followed the instructions except importing the notebook because I just want NAO to utilize the Watson conversation services. I have been getting this error anyone knows how to fix it?

[ERROR] behavior.box :_safeCallOfUserMethod:281 _Behavior__lastUploadedChoregrapheBehaviorWatsonSTT885062920__root__WatsonSTT_25: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/naoqi.py", line 271, in _safeCallOfUserMethod
    func()
  File "<string>", line 20, in onInput_onStart
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

**Comment by bosdhill** [comment]
I get a similar error. Not sure how to fix it, either.

**Comment by RK-Sharath** [comment]
Are you on Python 2x or 3x?

**Comment by erickzzh** [comment]
i am using 3.x

**Comment by RK-Sharath** [comment]
@ezmoneySniper Choregraphe works only with Python 2x. I am afraid there is no fix for this issue.

**Comment by RK-Sharath** [comment]
Documentation has been updated accordingly. Thank you.

**Comment by hanneshoettinger** [comment]
Seems like it is an old SSL protocol that is not supported anymore by the IBM services or any other HTTPS API call. Nao uses OPEN SSL Version 1.0.0, which is not compatible with the services. We have connected Nao to a local Node-Red Service, that is forwarding the requests from Nao as a quick solution.

**Comment by BenjaminYeh83** [comment]
Hello, I am using 2.7 version and still having sam issue. Thank you

**Comment by RK-Sharath** [comment]
@ezmoneySniper You will have to modify the Node-RED flow to suit your requirement. The response from @hanneshoettinger should address the compatibility issue. Please let me know if you still face the problem.

**Comment by RK-Sharath** [comment]
@ezmoneySniper please refer to steps 5 & 6 in the documentation for updated Node-RED flows. Kindly let me know if you face any issue.

**Comment by Jultrocor** [comment]
Hello, I am getting the same error using the updated node-RED json flows. I'm going over and over steps 5 & 6 but I can't get past the error. Is there anything else that needs to be changed to correct this?

**Comment by RK-Sharath** [comment]
@jultrocor What is the error message

**Comment by Jultrocor** [comment]
@RK-Sharath Exactly the same in the very first comment:

[ERROR] behavior.box :_safeCallOfUserMethod:281 _Behavior__lastUploadedChoregrapheBehaviorWatsonSTT159779560__root__WatsonSTT_25: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/naoqi.py", line 271, in _safeCallOfUserMethod
    func()
  File "<string>", line 21, in onInput_onStart
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

I think I might have used some wrong old URL somewhere. Where exactly is the change you did to fix the issue?

**Comment by erickzzh** [comment]
Hey @RK-Sharath I have tried again and received the same error again. Same as @Jultrocor
